import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Titan Quiz Bowl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tuffyimage.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Titan Quiz Bowl!
        </h1>

        <div className={styles.grid}>
          <Link href="/posts/music" className={styles.card}/>
            <h2>Music &rarr;</h2>

          <Link href="/posts/geography" className={styles.card}/>
            <h2>Geography &rarr;</h2>

          <Link href="/posts/history" className={styles.card}/>
            <h2>History &rarr;</h2>

          <Link href="/posts/general" className={styles.card}/>
            <h2>General &rarr;</h2>

          <Link href="/posts/setting" className={styles.card}/>
            <h2>Settings &rarr;</h2>
            
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
